# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:

#######################################################################
# 订阅链接
- type: subscribe
  options:
    url: https://proxypoolss.tk/sip002/sub
- type: subscribe
  options:
    url: https://proxypoolss.tk/vmess/sub
- type: subscribe
  options:
    url: https://proxypoolss.tk/trojan/sub
- type: subscribe
  options:
    url: https://proxypoolss.tk/ssr/sub
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/sip002/sub
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/vmess/sub
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/trojan/sub
- type: subscribe
  options:
    url: https://proxypoolsstest.herokuapp.com/ssr/sub
- type: subscribe
  options:
    url: https://github.com/ssrsub/ssr/raw/master/ssrsub
- type: subscribe
  options:
    url: https://github.com/ssrsub/ssr/raw/master/ss-sub
- type: subscribe
  options:
    url: https://github.com/ssrsub/ssr/raw/master/v2ray
- type: subscribe
  options:
    url: https://bee2.cloud//api/v1/client/subscribe?token=6da7a98ce790aff0292196062ffc301f

#==========================================================================
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-36-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-2-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-50-1.html
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-51-1.html
#==========================================================================
# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200
- type: tgchannel
  options:
    channel: ssrlist2
    num: 200
- type: tgchannel
  options:
    channel: ssrlists
    num: 200
- type: tgchannel
  options:
    channel: V2List
    num: 200
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200
